### REcuperar todas las peliculas

GET http://localhost:1234/movies

### Recuperar una pelicula por ID
GET http://localhost:1234/movies/9e6106f0-848b-4810-a11a-3d832a5610f9

### Recuperar todas las peliculas por genero

GET http://localhost:1234/movies?genre=drama

### Crear una Pelicula con POST

POST http://localhost:1234/movies
Content-Type: application/json

  {
    "sql": "SELECT * FROM users",
    "tittle": "Pulp Fiction",
    "year": 1994,
    "director": "Nahuel Riverossss",
    "duration": 154,
    "poster": "https://www.themoviedb.org/t/p/original/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    "genre": [
      "Crime",
      "Drama"
    ]
  }

### Actualizar una pelicula

PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

  {
    "year": 2024
  }  